
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///world?serverTimezone=UTC
    username: root
    password: 123456

  redis:
    host: 47.98.249.203
    port: 6379
    password: 123321
    database: 1
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #type-aliases-package: com/like4u/papermanager/pojo

mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
server:
  port: 8090